# Generated by Django 3.0.4 on 2020-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200318_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='item',
            new_name='item_id',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'Tv Show')], default='movie', max_length=200),
        ),
    ]
