# Generated by Django 3.0.4 on 2020-03-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200321_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='avatar_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
