# Generated by Django 3.0.4 on 2020-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200321_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='avatar_img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
